### ISSUE TITLE
New online user record message

### ISSUE THREAD

**Issue by joey-colon** [cs-discord-at-ucf/lion#119]
Send a message to some channel when we achieve a new "online users" record

**Comment by tanndlin** [comment]
Gonna do this within a week or 2 as well, unless @Armintron wants it

**Comment by Armintron** [comment]
By online users, does that just mean the total number of members in the discord or members that are actually online? I'm assuming the former

**Comment by c650** [comment]
up to you, but the total in the server seems better to me

**Comment by joey-colon** [comment]
it's total concurrent online

**Comment by joey-colon** [comment]
total in the server sounds too spammy. for a good amount of times a new user joins, we would be emitting a new record message. makes sense to track online count
