### ISSUE TITLE
frequently suggested server requests

### ISSUE THREAD

**Issue by joeydotdev** [cs-discord-at-ucf/lion#128]
create a plugin where a user can type `!serverrequests` or something. lion should respond back with a frequently "suggested" ideas embed that includes an answer to the ideas so a user can read through before suggesting their idea.

eventually, we will need to implement a datastore for this as well as for #126. i can set this part up when i have time

**Comment by tanndlin** [comment]
Someone want to create a list of the commonly asked things?

**Comment by c650** [comment]
should be dynamic

**Comment by tanndlin** [comment]
I'd love it to be, but idk how to get something like that dynamically from the channel

**Comment by tanndlin** [comment]
Closing because of a more recent issue #656 , which is this but more modern issue, with a little more up-to-date info
