### ISSUE TITLE
Hurricane/Weather Events Plugin

### ISSUE THREAD

**Issue by c650** [cs-discord-at-ucf/lion#171]
It would be cool to have: a **job** that checks for hurricane advisories; a command to output status of a hurricane or the Atlantic in general; etc.

API: https://www.weather.gov/documentation/services-web-api#/default/get_alerts_active

**Comment by tanndlin** [comment]
Could also make this a job so that it alerts when something severe is coming

**Comment by c650** [comment]
> Could also make this a job so that it alerts when something severe is coming

That’s a splendid idea. Hurricane season is upon us

**Comment by tanndlin** [comment]
About to work on this with Cleverwolf soon
