### ISSUE TITLE
Animal image plugins

### ISSUE THREAD

**Issue by zenith110** [cs-discord-at-ucf/lion#207]
So after making the raccoon plugin, I realized that I'd want to make a fox plugin. The issue is that they're exactly the same code wise for a plugin. All I need to do is change the route and change the name in the response. I'm thinking it'd be better to do something like a 
[general_plugin] -> arg, with the argument providing the route, I'm just not sure if this would be safe.

**Comment by c650** [comment]
need more info about the architecture. How will you abstract `AnimalPlugin`?

**Comment by zenith110** [comment]
The site I have for the images is simply routes with the routes leading to a s3 bucket. The only thing I'd need to change for the code would be line 14 which is the _API_URL to include the animal name, and line 27 which is the image itself, swapping out "raccoon" for example for fox.

**Comment by c650** [comment]
There must be an API agnostic abstraction and then minimal implementations to work with some specific API...
