### ISSUE TITLE
ModerationService use Client.fetch_user instead of Guild user lookup

### ISSUE THREAD

**Issue by c650** [cs-discord-at-ucf/lion#236]
https://github.com/joey-colon/lion/blob/b4b28e8790bf9c62b1c0f6d8b133450634a75dd3/src/services/moderation.service.ts#L13-L19

currently when a user is banned we can no longer look them up.

**Comment by tanndlin** [comment]
https://stackoverflow.com/questions/56834914/how-can-i-show-an-banlist-from-all-banned-users
