### ISSUE TITLE
Dynamic Audio Channel Creation

### ISSUE THREAD

**Issue by curtishelsel** [cs-discord-at-ucf/lion#307]
I would like to have users have the ability to make temporary voice chats for their classrooms by calling a command. Something like !classvoicechat in their class channel and it would make #classcode_professor_voice in a Class Voice Chat category.

Requirements:
1. Create a voice channel in a newly created Class Voice Chat category from the class channel.
2. Default to private channel and mirror permissions of the class channel into the audio channel. Only those that can see the audio channel are the ones that are currently registered for the class through bot_commands. 
3. Put the calling user into the channel when the call is made. 
4. Remove the channel after a set time of inactivity. I think something like when the last person leaves the channel, 5 minutes later the channel is deleted. It can be shorter, 1 minute even. I just want to make sure they don't clog up the server with people making random channels and walking away from them.
5. I don't know if it will ever come up but if more than one student wants to make a voice channel it can be a progressive numbering scheme. #classcode_professor_voice1, #classcode_professor_voice2, #classcode_professor_voice3 etc. 

Feel free to name the command something cooler.

**Comment by c650** [comment]
https://github.com/cscareers-dev/discord-chanserv
