### ISSUE TITLE
Improve Roles commands

### ISSUE THREAD

**Issue by LockedThread** [cs-discord-at-ucf/lion#316]
Remove the top 3 roles from showing.
<img width="170" alt="Screen Shot 2021-02-12 at 12 29 02 PM" src="https://user-images.githubusercontent.com/42919066/107801309-e5b91500-6d2d-11eb-9503-5f293cdbcb3c.png">

Allow the !addroles command to be executed in the dm with the bot; it only makes sense to do that if you're going to have the bot send you a dm.

**Comment by tanndlin** [comment]
Fixed by #357
Can't do DM for adding roles, because that adds to the debt
