### ISSUE TITLE
crypto price change % should be *100

### ISSUE THREAD

**Issue by c650** [cs-discord-at-ucf/lion#317]

**Comment by tanndlin** [comment]
https://github.com/cs-discord-at-ucf/lion/blob/8a8edf08db25499673a0c534513292ab81896201/src/app/plugins/price.plugin.ts#L86
Is this not what it should be?

**Comment by c650** [comment]
Perhaps the change is misleading because I’ve only ever seen it be very small. Idk what time frame it is about
