### ISSUE TITLE
CircleCI Uses npm install instead of npm ci

### ISSUE THREAD

**Issue by Helithumper** [cs-discord-at-ucf/lion#322]
Currently, CircleCI uses `npm install`. This is not best practice as it ignores the `package_lock.json` and will update packages during the build process. Changing this out for `npm ci` should fix this issue.

**Comment by Helithumper** [comment]
Fixed by https://github.com/cs-discord-at-ucf/lion/pull/323

**Comment by c650** [comment]
pro tip if you say `Fixes #...` in the PR itll auto-close this
