### ISSUE TITLE
Reaction stopped being removed from Paged Embeds

### ISSUE THREAD

**Issue by tanndlin** [cs-discord-at-ucf/lion#387]
noticed it happen yesterday (5/15) and again today
 So likely to broke with latest deploy
![image](https://user-images.githubusercontent.com/39809146/118405726-a658d800-b63e-11eb-9628-99a31054096b.png)

**Comment by tanndlin** [comment]
I believe the bot is crashing often, thus losing the listeners that it uses to remove the reactions

**Comment by c650** [comment]
afb0251418b9ebac8317186b88b1754efc73410f
