### ISSUE TITLE
Update Createclassvoice

### ISSUE THREAD

**Issue by curtishelsel** [cs-discord-at-ucf/lion#391]
- Remove invite link so only reacts will show the channel. Potentially with the same embed style as broadcast.
- Create a class_voice category at the top of the class categories (above Grad-Classes) for easier visibility of the newly created voice chat
- place temp voice chats in this category instead of audio channels

**Comment by tanndlin** [comment]
👍
I will go ahead and add the category so that we dont crash the bot 600 times again

**Comment by tanndlin** [comment]
Fixed by #393
