### ISSUE TITLE
Fuzzy search should remove reaction and dispose collector upon react

### ISSUE THREAD

**Issue by tanndlin** [cs-discord-at-ucf/lion#398]

**Comment by tanndlin** [comment]
It should also edit the message to say "successfully... " just like any other register message

**Comment by CallumCoy** [comment]
If we implement this exactly to what you want then we will have to give register and unregister their own reaction message function.  I have tried implementing a rough version that could be used universally that I'll push what I have for you to see if that is close enough.

**Comment by CallumCoy** [comment]
After sleeping on it again, another option that would allow this and still keep a universal reaction message.  Would be to get register and unregister to send a message for each unfound class.  Although with up to 10 classes been an option it may be a bit spammy.

**Comment by tanndlin** [comment]
You can only register for 5 at once, let alone the fact that most people almost exclusively do one class at a time. You can also add a dismiss react on the end, that edits the message to just say dismissed or whatever so it becomes smaller

**Comment by tanndlin** [comment]
Fixed by #404
