### ISSUE TITLE
image plugins sometimes give files

### ISSUE THREAD

**Issue by CallumCoy** [cs-discord-at-ucf/lion#399]
Check the returning file and make sure it either has a .jpg or .png at the end of it, and plug one in if not.

**Comment by tanndlin** [comment]
Example of this happening?

**Comment by VijayStroup** [comment]
View `src/app/plugins/ariana.plugin.ts` line 70 where I reply; this is how you fix that error.

**Comment by CallumCoy** [comment]
![image](https://user-images.githubusercontent.com/10034057/118728518-4c087480-b802-11eb-9765-d1ddd9878989.png)
Right there

**Comment by VijayStroup** [comment]
```js
await message.reply('', {
  files: [{
    attachment: file,
    name: 'image.jpg'
  }]}
);
```
The `name` parameter is key here. Using `.jpg` will tell discord it is a picture and embed it as a normal picture instead of a file.
