### ISSUE TITLE
Make Abstract for game plugins

### ISSUE THREAD

**Issue by tanndlin** [cs-discord-at-ucf/lion#450]
Make a template for game plugins to minimize duplicate code and easy of use for implementing leaderboards for different games

**Comment by TylerMathis** [comment]
What would this target? Just leaderboard implementation, or a full abstract for game rendering in general?

**Comment by Armintron** [comment]
It would also involve getting the opponent(s).

**Comment by TylerMathis** [comment]
Ah gotcha, so just like a helper suite for games?

ie we could do `const opponents = GameHelper.getOpponents(message)` ? Or are we thinking something more abstract

**Comment by joey-colon** [comment]
what operations would this game class have? not convinced that its a good step

**Comment by joey-colon** [comment]
> It would also involve getting the opponent(s).

we cant assume all games will have opponents (e.g. tic tac toe)

**Comment by Armintron** [comment]
> > It would also involve getting the opponent(s).
> 
> we cant assume all games will have opponents (e.g. tic tac toe)
> 

That's why the s is in ( ).

**Comment by tanndlin** [comment]
I'll just add this to the backlog until we have a need for it

**Comment by tanndlin** [comment]
Can reopen when this gets picked back up
