### ISSUE TITLE
Tik Tok Plugin

### ISSUE THREAD

**Issue by suneettipirneni** [cs-discord-at-ucf/lion#456]
Basically show CS themed tik toks

**Comment by Armintron** [comment]
Anyone have a good API to do this? I looked for days and couldn't find anything that works.

**Comment by tanndlin** [comment]
3rd Party Content scary

**Comment by suneettipirneni** [comment]
I'm going to close this because I think it's more effort than its worth, if someone finds a feasible way of doing this, it can be reopened.
