### ISSUE TITLE
Do fizzBuzz in #counting

### ISSUE THREAD

**Issue by c650** [cs-discord-at-ucf/lion#529]
If one of yall codes this wrong lol rip

**Comment by tanndlin** [comment]
How should this be done with a reply? Could get spammy but not against it
We could have `fizz` and `buzz` emotes for reacting

**Comment by Armintron** [comment]
I like the emoji reacts

**Comment by c650** [comment]
Fizz and Buzz just like the Bruh and Yeet emotes, with F and B as backup
