### ISSUE TITLE
Update !register embed

### ISSUE THREAD

**Issue by curtishelsel** [cs-discord-at-ucf/lion#552]
Add a call to action to the embed so the user is aware that they should click on one of the emotes (or button if we set that up). 
Add @mention for the user so they are aware of the response.

"@user Did you mean <class_code>? Click yes to be registered for course channel. Click no to cancel."

**Comment by tanndlin** [comment]
[https://github.com/cs-discord-at-ucf/lion/commit/0c1b9bde672582f1f2167654b34000315d0d0cde](fixed)
