### ISSUE TITLE
Increase automated bans

### ISSUE THREAD

**Issue by tanndlin** [cs-discord-at-ucf/lion#568]
Currently after 3 warns in a week, its a 7-day ban (**Change this to 2 weeks**)
I also want to kick the user and notify them the 4th time (no matter the time span)
And ban someone the >=5th time (no time limit)

It takes a lot to get to 5 warns, there has to be something wrong to get there

**Comment by tanndlin** [comment]
Should probably let someone know when they get warned
```
This is your **X** warn
4 is a kick
5 is a ban
```
something a little more formal than that

**Comment by Kurtoid** [comment]
The sudden jump from kick->ban seems excessive

**Comment by Kurtoid** [comment]
To elaborate: you have 5 blacklisted words (all urls) that can easily come up in conversation. There's no documentation that these are blacklisted. It's perfectly convincible that someone could ban themselves by mentioning these everyday URLs

**Comment by tanndlin** [comment]
> To elaborate: you have 5 blacklisted words (all urls) that can easily come up in conversation. There's no documentation that these are blacklisted. It's perfectly convincible that someone could ban themselves by mentioning these everyday URLs

you get notified everytime you send a link that its not allowed

**Comment by Kurtoid** [comment]
But you done know a link is banned until you post it. Since there's 5, it's possible to ban yourself without knowing any of them. The solution would be to make it transparent - actually put the blacklist in the #rules channel

**Comment by Kurtoid** [comment]
> > To elaborate: you have 5 blacklisted words (all urls) that can easily come up in conversation. There's no documentation that these are blacklisted. It's perfectly convincible that someone could ban themselves by mentioning these everyday URLs
> 
> you get notified everytime you send a link that its not allowed

I'm well aware :p

**Comment by curtishelsel** [comment]
The message regarding sending server invites is not the same as a warning. Warnings are distinct code of conduct violations that are issued by moderators and delivered by lion. If someone posts a server invite, it's not against the code of conduct. Lion sends a message that we don't allow external server invites and deletes the message. However, sending a server invite multiple times is considered spam/advertising which is against code of conduct and results in a moderator issuing the warning.

**Comment by Kurtoid** [comment]
Ok, that makes sense - I guess I mis-read the blacklist code
