### ISSUE TITLE
Archive class channels in some manner and allow users to access them at the end of a semester

### ISSUE THREAD

**Issue by TheIceCreamBear** [cs-discord-at-ucf/lion#629]
It would be a nice QoL feature to archive the class channels at the end of the semester. Some of the content in the class channels can be very useful, or just really cool. At the end of the semester, all of the content posted is lost.

It would be nice to have a way to view the channel at the end of the semester in some fashion. While warnings are given that the channel will be deleted, not all users have the ability to go and save the stuff they want. It is also possible for a user to forget to grab something or think it isn't worth it and regret not having it after the channels are deleted.

Possible Implementation steps (modified from @Armintron):
1. Log all messages and/or pins in a given class channel to a database
2. At archival time, take a snapshot of the users who are allowed to access the channel, this will be the list of allowed users
3. Create some method of retrieving the stored messages and/or pins for a given channel, and check that the accessor is on the list of allowed users

**Comment by Armintron** [comment]
https://github.com/Tyrrrz/DiscordChatExporter this repo may be of use for this

**Comment by c650** [comment]
Can you add suggested implementation steps to summarise discussion in discord

**Comment by Armintron** [comment]
1. Before channels are deleted, the current users in a class channel are added to a list of people that can access the archives for that channel.
2. Using Lion, the channels and their pins are stored in the database
3. An endpoint is created that can (given credentials that are allowed to access the request archieve) fetch an archive

> Can you add suggested implementation steps to summarise discussion in discord

**Comment by TheIceCreamBear** [comment]
Closing this because I personally dont want to dedicate time to do this and I dont think there will be much traction on this going forward.
