### ISSUE TITLE
Point System

### ISSUE THREAD

**Issue by tanndlin** [cs-discord-at-ucf/lion#630]
- Users are awarded a point every time they do something
    - Sending messages
    - Getting reactions? Like Reddit karma 
- A Plugin that a user can play with the gamble their points
    - ie: a coinflip to double or lose betted amount
- Leaderboard to see who has the most points
    - Similar to the C4 and TTT leaderboards

**Comment by tanndlin** [comment]
Would be nice to have some kind of PvP for point wagers

**Comment by suneettipirneni** [comment]
This sounds like something people would farm just to get to the top of the leaderboard.

**Comment by tanndlin** [comment]
We can just not allow points through messages

**Comment by tanndlin** [comment]
Could also award points for winning in C4 or TTT

**Comment by c650** [comment]
You could have points decay over time
