### ISSUE TITLE
Build wouldn't start after this PR

### ISSUE THREAD

**Issue by tanndlin** [cs-discord-at-ucf/lion#648]
[PR](https://github.com/cs-discord-at-ucf/lion/pull/643)
Not really sure what was happening, but i reverted the pr and worked afterwards

**Comment by tanndlin** [comment]
Prob bc of all the package.json changes

**Comment by suneettipirneni** [comment]
Can't really solve this without any error logs.

**Comment by tanndlin** [comment]
Lets start by making a PR of *code* and not changing node versions and DJS versions at the same time so we can isolate the problem

**Comment by suneettipirneni** [comment]
> Lets start by making a PR of *code* and not changing node versions and DJS versions at the same time so we can isolate the problem

I didn't change the node version 🤔

**Comment by c650** [comment]
@suneettipirneni you have the dockerfile. Can you try running in docker and see what happens? 

@tanndlin you can share the logs yeah?

**Comment by tanndlin** [comment]
There werent logs for some reason, get it gets stuck deploying, it just restarts over and over and nothing in Papertrail
plus the build passed which is where the logs normally come from when versions are an issue

**Comment by c650** [comment]
Ok let’s try docker container locally and see how it goes

**Comment by suneettipirneni** [comment]
We'll circle back to this once lion has proper error handling.
