### ISSUE TITLE
Add a ping for gradstudent and alumni roles

### ISSUE THREAD

**Issue by curtishelsel** [cs-discord-at-ucf/lion#666]
Ping the user in either #grad_cafe or #alumni_lounge when they add the role so they can be made aware of the role access channels. It can have some kind of variable message to go along with it so it's not just a user ping.

Random examples:
"Congratulations @user on all your hard work!"
"You made it, @user! Congratulations"
“Congratulations and BRAVO, @ user!”
“This calls for celebrating! Congratulations @user!”
“You did it! Congrats @user!”
“Caps off to you, Graduate! Well done, @user!”

**Comment by pedrofcarvalho** [comment]
This is a test, trying to assign myself to this issue

**Comment by bluffdev** [comment]
Shouldn't this issue be closed since the feature was added already?

**Comment by pedrofcarvalho** [comment]
yeah, it should. I don't know it didn't close

**Comment by c650** [comment]
If you write “fixes #…” in the commit then it auto closes

**Comment by pedrofcarvalho** [comment]
Ah nice, will do it next time. Thanks
