### ISSUE TITLE
Add Lion to new channels

### ISSUE THREAD

**Issue by tanndlin** [cs-discord-at-ucf/lion#667]
When `addclasschans` is ran, Lion should add him self in the list of perms so that we can remove his admin privileges.
Currently, without admin privileges it cannot see messages in class channels.

**Comment by tanndlin** [comment]
Would be pretty easy for someone new to do

**Comment by c650** [comment]
Why is this necessary

**Comment by tanndlin** [comment]
> Why is this necessary 

Right now it has to have admin perms to see the channels, which means we can't take away certain perms. Namely, pinging everyone

**Comment by c650** [comment]
Lol did you reas joey’s blog? Okay I guess.

**Comment by tanndlin** [comment]
Actually Curtis mentioned it early today, and I was like yeah we probably should. Promptly forgot, then yeah I stumbled on his blog and it reminded me about it 😂

**Comment by c650** [comment]
Hack lion to run a job that gives itself perms in every channel. Then you can revoke admin if you really want. I don’t think you should though

**Comment by tanndlin** [comment]
> Hack lion to run a job that gives itself perms in every channel. Then you can revoke admin if you really want. I don’t think you should though

Any reason not to? Just curious

**Comment by c650** [comment]
It’s effort

**Comment by tanndlin** [comment]
fair
