### ISSUE TITLE
Make a backend method for validating a string as User ID

### ISSUE THREAD

**Issue by tanndlin** [cs-discord-at-ucf/lion#671]
Make some kind of method that lives in [Moderation.Helpers](https://github.com/cs-discord-at-ucf/lion/blob/5ecae6c2c9aa6169a3e18203040489bc1004eb46/src/services/moderation.service.ts#L26).

Just takes in a string and uses regex (that you can rip from [checkclasses](https://github.com/cs-discord-at-ucf/lion/blob/eb3d25314da00e7474ddda6a7e7fae643d050576/src/app/plugins/checkclasses.plugin.ts#L14)) `^(([^#]+#\d{4})|\d{17,18})$` to test the string.
And can just repurpose the `checkclasses.test.ts` for testing that new method.

Then we can use this method for validating input for plugins without coding it manually

**Comment by bquach2** [comment]
Hi, I was looking at this project and was interested in working on this issue along with potentially a few others. Could I be assigned this task?

**Comment by tanndlin** [comment]
> Hi, I was looking at this project and was interested in working on this issue along with potentially a few others. Could I be assigned this task?

Absolutely, great to have some new blood!

**Comment by bquach2** [comment]
Hi Tanndlin, I am trying to build and run and am running into an issue, is there a way for me to contact you like discord or something?

**Comment by tanndlin** [comment]
> Hi Tanndlin, I am trying to build and run and am running into an issue, is there a way for me to contact you like discord or something?

Yeah for sure, `Tanndlin#4450`
