### ISSUE TITLE
Command to merge 2 accounts warns

### ISSUE THREAD

**Issue by tanndlin** [cs-discord-at-ucf/lion#685]
When someone makes an alt, their previous warns should carry over.
Make a plugin that takes 2 ID's and moves all the previous warns to the new account

Should prob be admin only, as it changes past records

**Comment by c650** [comment]
I prefer you make an alts Collection instead instead of copying/overwriting a bunch of records

**Comment by tanndlin** [comment]
> I prefer you make an alts Collection instead instead of copying/overwriting a bunch of records

I like that idea

**Comment by tanndlin** [comment]
Fixed by #706
