### ISSUE TITLE
Usernames are Changing

### ISSUE THREAD

**Issue by tanndlin** [cs-discord-at-ucf/lion#759]
https://discord.com/blog/usernames

Yikes lol

**Comment by tanndlin** [comment]
[Discord's](https://support-dev.discord.com/hc/en-us/articles/13667755828631#h_01GYA87X9QZ19H2X6PJ3M35ZDH) 2 cents on what code this will affect

**Comment by c650** [comment]
the changed rolled out. are we ok?

**Comment by tanndlin** [comment]
Yeah we seem ok, we store ID's in the DB. Only problem is most of our commandPatterns are for the old tag version

so idk how the mods are doing that. I tried to move support to IDs a while ago but not sure if I got all the plugins

**Comment by c650** [comment]
i think that's ok. if a command breaks, we move it to {#773}

**Comment by c650** [comment]
we survived.
