### ISSUE TITLE
move all plugins to slash_plugins

### ISSUE THREAD

**Issue by c650** [cs-discord-at-ucf/lion#773]
following the discussion in #768 , one by one we can migrate plugins/ to slash_plugins/ . once a plugin is migrated, delete it from plugins/.

these are the outstanding plugins:
- [x] addclasschans.plugin.ts
- [x] addroles.plugin.ts
- [x] alt.plugin.ts
- [x] anonreport.plugin.ts
- [x] broadcast.plugin.ts
- [x] bubblewrap.plugin.ts
- [x] cat.plugin.ts
- [x] chanban.plugin.ts
- [x] checkclasses.plugin.ts
- [x] cointoss.plugin.ts
- [x] connectfour.plugin.ts
- [x] controller.plugin.ts
- [x] countingLeaderboard.plugin.ts
- [x] createclassvoice.plugin.ts
- [x] delclasschans.plugin.ts
- [x] delroles.plugin.ts
- [x] diceroll.plugin.ts
- [x] dog.plugin.ts
- [x] equation.plugin.ts
- [x] gamble.plugin.ts
- [x] garage.plugin.ts
- [x] give.plugin.ts
- [x] help.plugin.ts
- [x] leaderboard.plugin.ts
- [x] lionpresence.plugin.ts
- [x] listclasses.plugin.ts
- [x] listroles.plugin.ts
- [x] manageroles.plugin.ts
- [x] marketplace.plugin.ts
- [x] modreport.plugin.ts
- [x] pointLeaderboard.plugin.ts
- [x] points.plugin.ts
- [x] poll.plugin.ts
- [x] register.plugin.ts
- [x] scores.plugin.ts
- [x] shadowban.plugin.ts
- [x] slowmode.plugin.ts
- [x] storepins.plugin.ts
- [x] ta.plugin.ts
- [x] tictactoe.plugin.ts
- [x] unregister.plugin.ts
- [x] users.plugin.ts

**Comment by tanndlin** [comment]
gg ez
