### ISSUE TITLE
Plugin to reinitialize slash commands

### ISSUE THREAD

**Issue by tanndlin** [cs-discord-at-ucf/lion#777]
A plugin to call `ISlashCommand#initialize` would probably be useful in the future in case any APIs fail to respond on startup.

Refs #776

**Comment by c650** [comment]
mmmm i disagree. plugins should be able to manage any of their own state. if something fails to initialise the first time, it should defer its interactions while it tries again.

**Comment by rob-3** [comment]
It's not clear to me that `initialize()` is actually needed. Can we not just fetch every time or just on the first call to the plugin?

**Comment by tanndlin** [comment]
> It's not clear to me that `initialize()` is actually needed. Can we not just fetch every time or just on the first call to the plugin?
> 
> 
> 
> The less in-memory state we maintain, the fewer strange states the bot can get into.

Pros and cons, in the past we typically have tried to minimize API calls since they can be slow so we can speed up response time. Plus it only needs to succeed once to seed the rest of the plug-in calls until restart

**Comment by rob-3** [comment]
> Pros and cons, in the past we typically have tried to minimize API calls since they can be slow so we can speed up response time. Plus it only needs to succeed once to seed the rest of the plug-in calls until restart

Are we worried that the API call response will change? We could just curl the data into JSON and paste it into the plugin if we are never invalidating the cache anyway. If the data rarely but sometimes changes, why not cache it in DB and periodically refetch?

I don't think `initialize()` is an idea that's never useful, but from the plugins I've seen I don't think we need it.

There's also just
```ts
let firstTime = true;
// ...
execute() {
  if (firstTime) {
    firstTime = false;
    // do stuff
  }
}
```

**Comment by tanndlin** [comment]
> > Pros and cons, in the past we typically have tried to minimize API calls since they can be slow so we can speed up response time. Plus it only needs to succeed once to seed the rest of the plug-in calls until restart
> 
> Are we worried that the API call response will change? We could just curl the data into JSON and paste it into the plugin if we are never invalidating the cache anyway. If the data rarely but sometimes changes, why not cache it in DB and periodically refetch?
> 
> I don't think `initialize()` is an idea that's never useful, but from the plugins I've seen I don't think we need it.
> 
> There's also just
> 
> ```ts
> let firstTime = true;
> // ...
> execute() {
>   if (firstTime) {
>     firstTime = false;
>     // do stuff
>   }
> }
> ```

Yeah thats the current pattern, I was just trying to find a way to semantically do this pattern without polluting the `execute` function. It's fine without it if we don't think its necessary.

**Comment by rob-3** [comment]
> Yeah thats the current pattern, I was just trying to find a way to semantically do this pattern without polluting the `execute` function. It's fine without it if we don't think its necessary.

It's up to you. My opinion is that it's not necessary and actually a better design without `initialize()`. I don't think a flag and if in (I think just 2) plugins is a serious problem. I think it's better to limit the plugin API surface and be careful about what abstractions are introduced.

One other option I thought of is to just do the fetching at the top level of the plugin files.

**Comment by tanndlin** [comment]
> One other option I thought of is to just do the fetching at the top level of the plugin files.

 True, I never thought about that. The *only* problem is that we wrap axios with our httpService, which you'd need the container for. It hasn't been that useful of wrapper so far, but I'd like to keep using the httpService incase we ever switch how we fetch data. That way we'd only need to change one file

**Comment by rob-3** [comment]
> The only problem is that we wrap axios with our httpService, which you'd need the container for.

We could make `container` a global and `export` it.

> It hasn't been that useful of wrapper so far

Agreed, this is why I'm skeptical of it.

> but I'd like to keep using the httpService incase we ever switch how we fetch data. That way we'd only need to change one file

This is true, but I don't think this benefit is worth the tradeoff. From the standpoint of a new contributor, I've never heard of `httpService` and the `container`. They are project-specific knowledge I have to pick up. What I do know is regular old `fetch` or Axios.

There's also the question of how valuable the benefit actually is. Have we *ever* switched the data fetching technique in the past? If we ever do need to, would doing a grand find-and-replace be super painful?

Maybe the point is to simplify tests, but we don't really have effective tests either. Most bugs make it to `develop` and some to production, and that's fine. There are also ways to mock/stub out global functions if that's what we want anyway.

I don't think `httpService` carries its weight, and I think introducing fewer abstractions would benefit the project. Slash commands are probably one of the biggest and most painful changes Lion has gone through. What has the `container` or any of these abstractions bought us in porting over commands? For me at least, negative value. It actually took me some time to consider how to expose `container` into the new design in a way that regular imports of library functions wouldn't. Even `IPlugin` failed us; we had to rewrite the plugin interface completely and port things.

I genuinely believe that getting rid of the `container` would be a big win for new contributors, and with the switch to slash commands, now is a good time to learn from some of the issues in the old codebase.

**Comment by rob-3** [comment]
I also dislike having to type `this.container` before every function I call :)

**Comment by c650** [comment]
i like the container and service abstractions because it makes it easier to change what e.g. http lib we use without updating a lot more code

i think nixing initialize() is ok too

to the point about we never re-initialize and maybe are dealing with stale data, it's up to the plugin author to know whether it should periodically renew whatever state it's maintaining
