### ISSUE TITLE
Help plugin will not recognize slash commands

### ISSUE THREAD

**Issue by tanndlin** [cs-discord-at-ucf/lion#778]
Help plugin uses the plugin store to find all registered plugins. 

Should be an easy fix to either pass in all the slash commands to the help commands initialize function when its migrated, or use FS to get all the plugins in the `slash_commands` folder

**Comment by c650** [comment]
do we need this? wouldn't the "/" in discord client automatically list all available slash cmds ?

**Comment by suneettipirneni** [comment]
> do we need this? wouldn't the "/" in discord client automatically list all available slash cmds ?

I concur

**Comment by tanndlin** [comment]
Sounds good
